name: plotting with annotations
on:
  push:
jobs:
  plotting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update apt-get
        run: sudo apt-get update
      - name: install build-essential, python3-dev, python3-full, python3-venv
        run: |
          sudo apt-get install -y build-essential
          sudo apt-get install -y python3-dev
          sudo apt-get install -y python3-full
          sudo apt-get install -y python3-venv
      - name: create venv
        run: python3 -m venv venv
      - name: update pip in venv
        run: |
          . venv/bin/activate
          python3 -m pip install --upgrade pip
      - name: install mpl into venv
        run: |
          . venv/bin/activate
          pip install matplotlib==3.8.0
      - name: plot with different combinations of backends, dpi
        run: |
          . venv/bin/activate
          python test.py --backend Agg --dpi 50
          python test.py --backend Agg --dpi 100
          python test.py --backend pgf --dpi 50
          python test.py --backend pgf --dpi 100
      - name: 'Upload PDFs as artifacts'
        uses: actions/upload-artifact@v3
        with:
          name: figures
          path: ./*.pdf
